"""empty message

Revision ID: 82aa0852296e
Revises: ef7760a3f32c
Create Date: 2022-08-17 09:31:19.721885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82aa0852296e'
down_revision = 'ef7760a3f32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
